### ISSUE TITLE
Chrome crashes

### ISSUE THREAD

**Issue by AgentVicman007** [andreagubellini/robotframework-docker#2]
Hello,

When I try to run Chrome I get below error. It works fine for fixfox. 
Chrome                                                                | FAIL |
WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

Please help

Thank you

**Comment by andreagubellini** [comment]
hey @AgentVicman007,

Have you tried adding the following capabilities?

--no-sandbox
--disable-gpu

also please share how you initialize your browser.

Thanks

**Comment by andreagubellini** [comment]
please @AgentVicman007  let me know if that solved the issue 👍

**Comment by AgentVicman007** [comment]
It solved the issue. Thank you very much
